Proye3JoseDRodriguezSemestreI2019/Models/Venta.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Proye3JoseDRodriguezSemestreI2019.Models
{
    public class Venta
    {
        public string correo { get; set; }
        public string total { get; set; }
        public string reserva { get; set; }
    }
}

Proye3JoseDRodriguezSemestreI2019/Controllers/CuentaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Proye3JoseDRodriguezSemestreI2019.Models;
using Microsoft.AspNetCore.Http; // Se incluye para poder hacer uso del session
using System.Net.Mail;
using System.Net;

namespace Proye3JoseDRodriguezSemestreI2019.Controllers
{
    public class CuentaController : Controller
    {
        //Variable necesaria para la conexion a db
        public IConfiguration Configuration { get; }

        public CuentaController(IConfiguration configuration)
        {
            Configuration = configuration;
        }//Constructor con archivo de conexion
        
        public ActionResult CrearCuenta()
        {
            return View("CrearCuentaView");
        }//retorna la vista principal de crear cuenta

        
        public ActionResult IniciarSesionAdmin()
        {
            return View("IniciarSesionAdminView");
        }//retorna la vista principal de iniciar sesion como admin

        public ActionResult cargarVistaCrearAdmin()
        {
            return View("CrearAdminView");
        }//retorna la vista principal de crear admin

        public ActionResult cargarVistaCrearVuelos()
        {
            List<String> lista_destinos = new List<String>();
            List<String> lista_aviones = new List<String>();
            string connectionString = Configuration["ConnectionStrings:DefaultConnection"];

            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                string sql = $"EXECUTE sp_obtener_destinos";
                string sql2 = $"EXECUTE sp_obtener_aviones";
                SqlDataReader reader;
                SqlDataReader reader2;
                using (SqlCommand command = new SqlCommand(sql, connection))
                {
                    command.CommandType = CommandType.Text;
                    connection.Open();
                    reader = command.ExecuteReader();
                    while (reader.Read())
                    {
                       lista_destinos.Add(reader[0].ToString());
                    }
                    
                }
                using (SqlCommand command = new SqlCommand(sql2, connection))
                {
                    command.CommandType = CommandType.Text;
                    reader2 = command.ExecuteReader();
                    while (reader2.Read())
                    {
                        lista_aviones.Add(reader2[0].ToString());
                    }

                }
                connection.Close();
            }
            
            //HttpContext.Session.SetString("destinos",lista_destinos[0]);
            ViewBag.Destinos = lista_destinos;
            ViewBag.Aviones = lista_aviones;
            return View("CrearVuelosView");
        }//retorna la vista principal de crear vuelos

        //Metodo usado para iniciar sesion en el modulo administrativo
        [HttpPost]
        public ActionResult Entrar(Administrador a)
        {
            int resultado = 0;
            string vista = "";
            System.Diagnostics.Debug.WriteLine(a.nombre_usuario);
            System.Diagnostics.Debug.WriteLine(a.contrasena);
            if (ModelState.IsValid)
            {
                string connectionString = Configuration["ConnectionStrings:DefaultConnection"];

                using (SqlConnection connection = new SqlConnection(connectionString))
                {
                    string sql = $"EXECUTE sp_inicio_sesion_admin @param_nombre = '{a.nombre_usuario}', @param_contrasena = '{a.contrasena}'";
                    SqlDataReader reader;
                    using (SqlCommand command = new SqlCommand(sql, connection))
                    {
                        command.CommandType = CommandType.Text;
                        connection.Open();
                        reader = command.ExecuteReader();
                        while (reader.Read())
                        {
                            resultado = reader.GetInt32(0);
                        }
                        connection.Close();
                    }
                }
            }

            if (resultado == 1)
            {
                System.Diagnostics.Debug.WriteLine("----------------------->LOGEADO");
                vista = "AdminView";
                HttpContext.Session.SetString("nombreAdmin",a.nombre_usuario);
                
            }
            else
            {
                vista = "Error";
            }

            return View(vista);
        }


        [HttpPost]
        public ActionResult crearNuevoAdmin(Administrador a)
        {
            int resultado = 0;
            string vista = "";
            string nombre = a.nombre_usuario;
            string contrasena = a.contrasena;
            System.Diagnostics.Debug.WriteLine("nombre "+nombre);
            System.Diagnostics.Debug.WriteLine("contrasena "+contrasena);
            if (ModelState.IsValid)
            {
                string connectionString = Configuration["ConnectionStrings:DefaultConnection"];

                using (SqlConnection connection = new SqlConnection(connectionString))
                {
                    string sql = $"EXECUTE sp_crear_admin @param_nombre = '{a.nombre_usuario}', @param_contrasena = '{a.contrasena}'";
                    using (SqlCommand command = new SqlCommand(sql, connection))
                    {
                        command.CommandType = CommandType.Text;
                        connection.Open();
                        resultado = command.ExecuteNonQuery();
                        connection.Close();
                    }
                }
            }

            if (resultado == 1)
            {
                vista = "AdminView";
            }
            else
            {
                vista = "Error";
            }

            return View(vista);
        }


        /*Metodo que genera el codigo de vuelo de acuerdo a la inicial del lugar de salida y del lugar de destino,
        seguido de un random de 4 digitos*/
        [HttpPost]
        public string generarCodigoVuelo(string select_salida, string select_destino)
        {
            string codido = select_salida[0].ToString() + select_destino[0].ToString();
            System.Diagnostics.Debug.WriteLine(codido);
            Random random = new Random();
            int n = random.Next(1000, 9999);
            codido = codido + n;
            return codido;
        }

        [HttpPost]
        public ActionResult crearVuelo(Vuelo v)
        {
            int resultado = 0;
            int resultado2 = 0;
            string vista = "";
            string codigo = v.codigo;
            string lugar_salida = v.lugar_salida;
            string destino = v.destino;
            string fecha_salida = v.fecha_salida;
            string fecha_llegada = v.fecha_llegada;
            string avion = v.avion;

            System.Diagnostics.Debug.WriteLine(codigo,lugar_salida+destino+fecha_salida+fecha_llegada+avion);

            if (ModelState.IsValid)
            {
                string connectionString = Configuration["ConnectionStrings:DefaultConnection"];

                using (SqlConnection connection = new SqlConnection(connectionString))
                {
                    string sql = $"EXECUTE sp_crear_vuelo @param_codigo = '{v.codigo}',@param_lugar_salida = '{v.lugar_salida}', @param_destino = '{v.destino}', @param_fecha_salida = '{v.fecha_salida}',@param_fecha_llegada = '{v.fecha_llegada}',@param_avion = '{v.avion}',@asientos = {15}";
                    string sql2 = $"EXECUTE insertar_vuelo_asientos @codigo_vuelo = '{v.codigo}'";
                    using (SqlCommand command = new SqlCommand(sql, connection))
                    {
                        command.CommandType = CommandType.Text;
                        connection.Open();
                        resultado = command.ExecuteNonQuery();
                        
                    }
                    using (SqlCommand command = new SqlCommand(sql2, connection))
                    {
                        command.CommandType = CommandType.Text;
                        resultado2 = command.ExecuteNonQuery();
                        
                    }
                    connection.Close();
                    
                }
            }

            if (resultado == 1 && resultado2 == 15)
            {
                vista = "AdminView";
            }
            else
            {
                vista = "Error";
            }

            return View(vista);
        }

        public ActionResult cargarVistaCrearDescuentos()
        {
            return View("CrearDescuentosView");
        }//retorna la vista principal de crear descuentos

        [HttpPost]
        public IActionResult crearDescuentos(Descuento d)
        {
            int resultado = 0;
            string vista = "";
            if (ModelState.IsValid)
            {
                string connectionString = Configuration["ConnectionStrings:DefaultConnection"];

                using (SqlConnection connection = new SqlConnection(connectionString))
                {
                    string sql = $"EXECUTE sp_crear_descuento @param_codigo = '{d.codigo}', @param_valor = {d.porcentaje_descuento}";
                    using (SqlCommand command = new SqlCommand(sql, connection))
                    {
                        command.CommandType = CommandType.Text;
                        connection.Open();
                        resultado = command.ExecuteNonQuery();
                        connection.Close();
                    }
                }
            }

            if (resultado == 1)
            {
                
                vista = "AdminView";
            }
            else
            {

Proye3JoseDRodriguezSemestreI2019/Views/Cuenta/AdminView.cshtml
@{
    ViewData["Title"] = "AdminView";
    Layout = "AdminNav";
}

<br>
<br>
<br>

<div class="container-fluid">
    <h1>Módulo administrativo</h1>
    <p>En este módulo puede encontrar la lista de acciones disponibles, seleccione la deseada para desplegar la vista respectiva</p>
    <hr />
    <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-4">

            <!-- Sidebar -->
            <div class="list-group" style="margin-bottom: 20px;">
                <a asp-controller="Cuenta" asp-action="cargarVistaCrearVuelos" class="list-group-item list-group-item-action">Crear vuelos</a>
                <a asp-controller="Cuenta" asp-action="cargarVistaCrearDescuentos" class="list-group-item list-group-item-action">Crear códigos de descuento</a>
                <a asp-controller="Cuenta" asp-action="cargarVistaVentas" class="list-group-item list-group-item-action">Ver informe de ventas</a>
                <a asp-controller="Cuenta" asp-action="cargarVistaCrearAdmin" class="list-group-item list-group-item-action">Crear nuevo administrador</a>
            </div>
        </div>
        <div class="col-lg-8 col-md-4 col-sm-4">
            <h5 class="card-title">UCR Airlines</h5>
            <hr id="hr"/>
            <h6 class="card-subtitle mb-2 text-muted">Bienvenido</h6>
            <p class="card-text">Podés crear nuevos administradores, crear vuelos y más en este módulo.</p>
            <br />
            <br />
        </div>

    </div>

</div>
<br>
<br>
<br>
<hr />
<style>
    a{
        color:red !important;
        font-weight:bold !important;
    }

    a:hover{
        font-size: 16px !important;
    }

    h5{
        text-decoration: underline !important;
        color:darkblue !important;
    }

    h1{
        color: darkblue !important;
    }

</style>

Proye3JoseDRodriguezSemestreI2019/Views/Cuenta/CrearAdminView.cshtml
@model Proye3JoseDRodriguezSemestreI2019.Models.Administrador
@{
    ViewData["Title"] = "CrearAdminView";
    Layout = "AdminNav";

}


<br>
<br>
<br>

<div class="container-fluid">
    <h1>Módulo administrativo</h1>
    <p>En este módulo puede encontrar la lista de acciones disponibles, seleccione la deseada para desplegar la vista respectiva</p>
    <hr />
    <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-4">

            <!-- Sidebar -->
            <div class="list-group" style="margin-bottom: 20px;">
                <a asp-controller="Cuenta" asp-action="cargarVistaCrearVuelos" class="list-group-item list-group-item-action">Crear vuelos</a>
                <a asp-controller="Cuenta" asp-action="cargarVistaCrearDescuentos" class="list-group-item list-group-item-action">Crear códigos de descuento</a>
                <a asp-controller="Cuenta" asp-action="cargarVistaVentas" class="list-group-item list-group-item-action">Ver informe de ventas</a>
                <a asp-controller="Cuenta" asp-action="cargarVistaCrearAdmin" class="list-group-item list-group-item-action">Crear nuevo administrador</a>
            </div>
        </div>
        <div class="col-lg-8 col-md-4 col-sm-4">
            <h5>Crear nuevo administrador</h5>
            <form id="crear_admin" asp-action="crearNuevoAdmin" method="post">
                <div class="form-group">
                    <label for="nombre_usuario">Nombre de usuario:</label>
                    <input type="text" class="form-control" id="nombre_usuario" name="nombre_usuario" required>
                </div>
                <div class="form-group">
                    <label for="contrasena">Contraseña</label>
                    <input type="password" class="form-control" id="contrasena" required>
                </div>
                <div class="form-group">
                    <label for="confirm_password_admin">Confirmar contraseña</label>
                    <input type="password" class="form-control" id="confirm_password_admin" name="contrasena" required>
                </div>
                <span id="confirm-message" class="confirm-message"></span>
                <br />
                <button type="submit" class="btn btn-primary" id="btn_registrar_admin" disabled>Registrar</button>
            </form>

        </div>

    </div>

</div>
<br>
<br>
<br>
<hr />
<script type="text/javascript">
    $(function () {
        $('#crear_admin [type="password"]').keyup(function () {

            var password = $('#contrasena');
            var confirm = $('#confirm_password_admin');
            var message = $('#confirm-message');
            var button = $('#btn_registrar_admin');


            var good_color = "#66cc66";
            var bad_color = "#ff6666";
            if (password.val() == confirm.val()) {
                confirm.css('background-color', good_color);
                message.css('color', good_color).html("Las contraseñas coinciden!");
                button.attr("disabled", false);
            } else {
                confirm.css('background-color', bad_color);
                message.css('color', bad_color).html("Las contraseñas no coinciden!");
                button.attr("disabled", true);
            }
        });
    });
</script>
<style>
    a {
        color: red !important;
        font-weight: bold !important;
    }

    h5 {
        color: darkblue !important;
        text-decoration: underline !important;
        text-decoration-color: darkblue !important;
    }

    h1 {
        color: darkblue !important;
    }
</style>

Proye3JoseDRodriguezSemestreI2019/Views/Cuenta/CrearCuentaView.cshtml
@model Proye3JoseDRodriguezSemestreI2019.Models.Cliente

<br>
<style type="text/css">

    .form-control {
        height: 40px;
        box-shadow: none;
        color: #969fa4;
    }

        .form-control:focus {
            border-color: #5cb85c;
        }

    .form-control, .btn {
        border-radius: 3px;
    }

    .signup-form {
        width: 400px;
        margin: 0 auto;
        padding: 30px 0;
    }

        .signup-form h2 {
            color: #636363;
            margin: 0 0 15px;
            position: relative;
            text-align: center;
        }

        .signup-form .hint-text {
            color: #999;
            margin-bottom: 30px;
            text-align: center;
        }

        .signup-form form {
            color: #999;
            border-radius: 3px;
            margin-bottom: 15px;
            background: #f2f3f7;
            box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
            padding: 30px;
        }

        .signup-form .form-group {
            margin-bottom: 20px;
        }

        .signup-form input[type="checkbox"] {
            margin-top: 3px;
        }

        .signup-form .btn {
            font-size: 16px;
            font-weight: bold;
            min-width: 140px;
            outline: none !important;
        }

        .signup-form .row div:first-child {
            padding-right: 10px;
        }

        .signup-form .row div:last-child {
            padding-left: 10px;
        }

        .signup-form a {
            color: #fff;
            text-decoration: underline;
        }

            .signup-form a:hover {
                text-decoration: none;
            }

        .signup-form form a {
            color: #5cb85c;
            text-decoration: none;
        }

            .signup-form form a:hover {
                text-decoration: underline;
            }
</style>

<div class="col-lg-12 col-sm-12 col-md-12">
    <div class="row">
        <div class="signup-form">
            <form asp-action="crearCuentaCliente" method="post">
                <h2>Registrarse</h2>
                <p class="hint-text">Crea tu cuenta. Es gratis y solo toma un minuto</p>
                <div class="form-group">
                    <input type="text" class="form-control" name="nombre_cliente" id="nombre_usuario" placeholder="Nombre Usuario" required="required">
                </div>
                <div class="form-group">
                    <input type="password" class="form-control" name="contrasena" id="contrasena" placeholder="Contraseña" required="required">
                </div>
                <div class="form-group">
                    <input type="email" class="form-control" name="correo" id="correo" placeholder="Correo" required="required">
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-danger btn-lg btn-block">
                        Registrarse
                    </button>
                </div>
            </form>
        </div>
    </div>

</div>

Proye3JoseDRodriguezSemestreI2019/Views/Cuenta/CrearDescuentosView.cshtml
@{
    ViewData["Title"] = "CrearDescuentosView";
    Layout = "AdminNav";
}

<br>
<br>
<br>

<div class="container-fluid">
    <h1>Módulo administrativo</h1>
    <p>En este módulo puede encontrar la lista de acciones disponibles, seleccione la deseada para desplegar la vista respectiva</p>
    <hr />
    <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-4">

            <!-- Sidebar -->
            <div class="list-group" style="margin-bottom: 20px;">
                <a asp-controller="Cuenta" asp-action="cargarVistaCrearVuelos" class="list-group-item list-group-item-action">Crear vuelos</a>
                <a asp-controller="Cuenta" asp-action="cargarVistaCrearDescuentos" class="list-group-item list-group-item-action">Crear códigos de descuento</a>
                <a asp-controller="Cuenta" asp-action="cargarVistaVentas" class="list-group-item list-group-item-action">Ver informe de ventas</a>
                <a asp-controller="Cuenta" asp-action="cargarVistaCrearAdmin" class="list-group-item list-group-item-action">Crear nuevo administrador</a>
            </div>
        </div>
        <div class="col-lg-8 col-md-4 col-sm-4">
            <h5>Crear nuevo descuento</h5>
            <form id="crear_descuento" asp-action="crearDescuentos" method="post">
                <div class="form-group">
                    <label for="nombre_usuario">Código</label>
                    <input type="text" class="form-control" id="codigo_descuento" name="codigo" required>
                </div>
                <div class="form-group">
                    <label for="porcentaje_descuento">Porcentaje de descuento</label>
                    <input type="number" class="form-control" id="porcentaje_descuento" name="porcentaje_descuento" required>
                </div>
                <button type="submit" class="btn btn-primary" id="btn_crear_descuento">Crear</button>
            </form>
        </div>

    </div>

</div>
<br>
<br>
<br>
<hr />
<style>
    a {
        color: red !important;
        font-weight: bold !important;
    }

        a:hover {
            font-size: 16px !important;
        }

    h5 {
        text-decoration: underline !important;
        color: darkblue !important;
    }

    h1 {
        color: darkblue !important;
    }
</style>

Proye3JoseDRodriguezSemestreI2019/Views/Cuenta/CrearVuelosView.cshtml
@{
    ViewData["Title"] = "CrearVuelosView";
    Layout = "AdminNav";
}

@using Microsoft.AspNetCore.Http;

<br>
<br>
<br>

<div class="container-fluid">
    <h1>Módulo administrativo</h1>
    <p>En este módulo puede encontrar la lista de acciones disponibles, seleccione la deseada para desplegar la vista respectiva</p>
    <hr />
    <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-4">

            <!-- Sidebar -->
            <div class="list-group" style="margin-bottom: 20px;">
                <a asp-controller="Cuenta" asp-action="cargarVistaCrearVuelos" class="list-group-item list-group-item-action">Crear vuelos</a>
                <a asp-controller="Cuenta" asp-action="cargarVistaCrearDescuentos" class="list-group-item list-group-item-action">Crear códigos de descuento</a>
                <a asp-controller="Cuenta" asp-action="cargarVistaVentas" class="list-group-item list-group-item-action">Ver informe de ventas</a>
                <a asp-controller="Cuenta" asp-action="cargarVistaCrearAdmin" class="list-group-item list-group-item-action">Crear nuevo administrador</a>
            </div>
        </div>
        <div class="col-lg-8 col-md-4 col-sm-4">
            <h5 class="card-title">Crear vuelos</h5>
            <form id="crear_vuelo" asp-action="crearVuelo" method="post">
                <div class="form-group">
                    <label for="">Lugar de salida:</label>
                    <select class="form-control" id="select_salida" name="lugar_salida">
                        @foreach (string s in ViewBag.Destinos)
                        {
                            <option value="@s">@s</option>
                        }
                    </select>
                </div>
                <div class="form-group">
                    <label for="">Lugar de destino:</label>
                    <select class="form-control" id="select_destino" name="destino">
                        @foreach (string s in ViewBag.Destinos)
                        {
                            <option value="@s">@s</option>
                        }
                    </select>
                </div>
                <div class="form-group">
                    <label for="">Fecha de salida:</label>
                    <input type="text" class="form-control" id="f_salida" name="fecha_salida" value="aaaa-mm-dd" required>
                </div>
                <div class="form-group">
                    <label for="">Fecha de llegada:</label>
                    <input type="text" class="form-control" id="f_llegada" name="fecha_llegada" value="aaaa-mm-dd" required>
                </div>

                <div class="form-group">
                    <label for="">Avión:</label>
                    <select class="form-control" id="select_avion" name="avion">
                        @foreach (string s in ViewBag.Aviones)
                        {
                            <option value="@s">@s</option>
                        }
                    </select>
                </div>
                <div class="form-group">
                    <label for="">Código:</label>
                    <input type="text" id="codigo_vuelo" name="codigo" value="" />
                    <button type="button" class="btn btn-primary" id="btn_generar_codigo">Generar</button>
                </div>
                <button type="submit" class="btn btn-primary" id="btn_registrar_vuelo">Registrar vuelo</button>
            </form>
            <br />
            <br />
        </div>

    </div>

</div>
<br>
<br>
<br>
<hr />
<script type="text/javascript">
    $(function () {
        $('#btn_generar_codigo').click(function (e) {
            var parametros = {
                "select_salida": $('#select_salida').val(),
                "select_destino": $('#select_destino').val()
            };
            $.ajax({
                type: "POST",
                url: '@Url.Action("generarCodigoVuelo")',
                data: parametros
            }).done(function (response) {
                //Successfully pass to server and get response
                $('#codigo_vuelo').val(response);
            });
        });

    });

</script>
<style>
    a {
        color: red !important;
        font-weight: bold !important;
    }

        a:hover {
            font-size: 16px !important;
        }

    h5 {
        text-decoration: underline !important;
        color: darkblue !important;
    }

    h1 {
        color: darkblue !important;
    }
</style>

Proye3JoseDRodriguezSemestreI2019/Views/Cuenta/IniciarSesionAdminView.cshtml
@model Proye3JoseDRodriguezSemestreI2019.Models.Administrador

<br>
<style type="text/css">

    .form-control {
        height: 40px;
        box-shadow: none;
        color: #969fa4;
    }

        .form-control:focus {
            border-color: #5cb85c;
        }

    .form-control, .btn {
        border-radius: 3px;
    }

    .signup-form {
        width: 400px;
        margin: 0 auto;
        padding: 30px 0;
    }

        .signup-form h2 {
            color: #636363;
            margin: 0 0 15px;
            position: relative;
            text-align: center;
        }

        .signup-form .hint-text {
            color: #999;
            margin-bottom: 30px;
            text-align: center;
        }

        .signup-form form {
            color: #999;
            border-radius: 3px;
            margin-bottom: 15px;
            background: #f2f3f7;
            box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
            padding: 30px;
        }

        .signup-form .form-group {
            margin-bottom: 20px;
        }

        .signup-form input[type="checkbox"] {
            margin-top: 3px;
        }

        .signup-form .btn {
            font-size: 16px;
            font-weight: bold;
            min-width: 140px;
            outline: none !important;
        }

        .signup-form .row div:first-child {
            padding-right: 10px;
        }

        .signup-form .row div:last-child {
            padding-left: 10px;
        }

        .signup-form a {
            color: #fff;
            text-decoration: underline;
        }

            .signup-form a:hover {
                text-decoration: none;
            }

        .signup-form form a {
            color: #5cb85c;
            text-decoration: none;
        }

            .signup-form form a:hover {
                text-decoration: underline;
            }
</style>

<div class="col-lg-12 col-sm-12 col-md-12">
    <div class="row">
        <div class="signup-form">
            <form asp-action="entrar" method="post">
                <h2>Inicia Sesión</h2>
                <div class="form-group">
                    <input type="text" class="form-control" name="nombre_usuario" id="nombre_usuario" placeholder="Nombre Usuario" required="required">
                </div>
                <div class="form-group">
                    <input type="password" class="form-control" name="contrasena" id="contrasena" placeholder="Contraseña" required="required">
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-danger btn-lg btn-block">
                        Entrar
                    </button>
                </div>
            </form>
        </div>
    </div>

</div>

Proye3JoseDRodriguezSemestreI2019/Views/Cuenta/VentasView.cshtml
@{
    ViewData["Title"] = "VentasView";
}


@{
    Layout = "AdminNav";
}

@using Proye3JoseDRodriguezSemestreI2019.Models;

<br>
<br>
<br>


<div class="container-fluid">
    <h1>Módulo administrativo</h1>
    <p>En este módulo puede encontrar la lista de acciones disponibles, seleccione la deseada para desplegar la vista respectiva</p>
    <hr />
    <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-4">

            <!-- Sidebar -->
            <div class="list-group" style="margin-bottom: 20px;">
                <a asp-controller="Cuenta" asp-action="cargarVistaCrearVuelos" class="list-group-item list-group-item-action">Crear vuelos</a>
                <a asp-controller="Cuenta" asp-action="cargarVistaCrearDescuentos" class="list-group-item list-group-item-action">Crear códigos de descuento</a>
                <a asp-controller="Cuenta" asp-action="cargarVistaVentas" class="list-group-item list-group-item-action">Ver informe de ventas</a>
                <a asp-controller="Cuenta" asp-action="cargarVistaCrearAdmin" class="list-group-item list-group-item-action">Crear nuevo administrador</a>
            </div>
        </div>
        <div class="col-lg-8 col-md-4 col-sm-4">
            <h5>Informe de ventas</h5>
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Correo</th>
                        <th>Total($)</th>
                        <th>Reserva</th>

                    </tr>
                </thead>
                <tbody id="content">
                    @foreach (Venta v in Model)
                    {
                        <tr>
                            <td>@v.correo</td>
                            <td>@v.total</td>
                            <td>@v.reserva</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>

    </div>

</div>
<br>
<br>
<br>
<hr />
<style>
    a {
        color: red !important;
        font-weight: bold !important;
    }

        a:hover {
            font-size: 16px !important;
        }

    h5 {
        text-decoration: underline !important;
        color: darkblue !important;
    }

    h1 {
        color: darkblue !important;
    }
</style>